import type { CompletionModel, CompletionOption } from "./model";

function flags(command: CompletionModel): string {
  return command.options.flatMap((option) => option.flags).join(" ");
}

function allOptions(model: CompletionModel): CompletionOption[] {
  return [model, ...model.subcommands].flatMap((command) => command.options);
}

export function render(model: CompletionModel): string {
  const commands = model.subcommands.map((command) => command.name).join(" ");
  const commandCases = model.subcommands
    .map((command) => `      ${command.name}) option_flags="${flags(command)}" ;;`)
    .join("\n");
  const choiceCases = new Map<string, string[]>();
  const fileFlags = new Set<string>();
  const directoryFlags = new Set<string>();

  for (const option of allOptions(model)) {
    for (const flag of option.flags) {
      if (option.kind === "choices") choiceCases.set(flag, option.choices);
      if (option.kind === "file") fileFlags.add(flag);
      if (option.kind === "directory") directoryFlags.add(flag);
    }
  }

  const valueCases = [
    ...Array.from(
      choiceCases,
      ([flag, choices]) =>
        `    ${flag}) COMPREPLY=( $(compgen -W "${choices.join(" ")}" -- "$cur") ); return ;;`,
    ),
    ...(fileFlags.size > 0
      ? [`    ${[...fileFlags].join("|")}) COMPREPLY=( $(compgen -f -- "$cur") ); return ;;`]
      : []),
    ...(directoryFlags.size > 0
      ? [`    ${[...directoryFlags].join("|")}) COMPREPLY=( $(compgen -d -- "$cur") ); return ;;`]
      : []),
  ].join("\n");
  const shells = model.subcommands
    .find((command) => command.name === "completions")
    ?.arguments.at(0)
    ?.choices.join(" ");

  return `# reddit-scrutinizer bash completions. Generated by \`reddit-scrutinizer completions bash\`.

_reddit_scrutinizer() {
  local cur prev subcommand option_flags i word
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  case "$prev" in
${valueCases}
  esac

  subcommand=""
  for ((i=1; i<COMP_CWORD; i++)); do
    word="\${COMP_WORDS[i]}"
    case "$word" in
      ${model.subcommands.map((command) => command.name).join("|")}) subcommand="$word"; break ;;
    esac
  done

  option_flags="${flags(model)}"
  case "$subcommand" in
${commandCases}
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "$option_flags" -- "$cur") )
    return
  fi

  case "$subcommand" in
    completions)
      COMPREPLY=( $(compgen -W "${shells ?? ""}" -- "$cur") )
      ;;
    serve)
      COMPREPLY=( $(compgen -f -- "$cur") )
      ;;
    "")
      COMPREPLY=( $(compgen -W "${commands}" -- "$cur") )
      while IFS= read -r directory; do COMPREPLY+=("$directory"); done < <(compgen -d -- "$cur")
      ;;
  esac
}

complete -F _reddit_scrutinizer reddit-scrutinizer
`;
}
