import type { CompletionModel, CompletionOption } from "./model";

function escape(value: string): string {
  return value.replaceAll("'", "\\'");
}

function optionLine(option: CompletionOption, condition?: string): string {
  const parts = ["complete -c reddit-scrutinizer"];
  if (condition) parts.push(`-n '${condition}'`);
  if (option.short) parts.push(`-s ${option.short.slice(1)}`);
  if (option.long) parts.push(`-l ${option.long.slice(2)}`);
  if (option.kind === "file") parts.push("-r");
  else if (option.kind !== "none") parts.push("-x");
  if (option.kind === "choices") parts.push(`-a '${option.choices.join(" ")}'`);
  if (option.kind === "file") parts.push("-F");
  if (option.kind === "directory") parts.push("-a '(__fish_complete_directories)'");
  parts.push(`-d '${escape(option.description)}'`);
  return parts.join(" ");
}

export function render(model: CompletionModel): string {
  const commandNames = model.subcommands.map((command) => command.name).join(" ");
  const rootCondition = `not __fish_seen_subcommand_from ${commandNames}`;
  const valueFlags = Array.from(
    new Set(
      [model, ...model.subcommands]
        .flatMap((command) => command.options)
        .filter((option) => option.kind !== "none")
        .flatMap((option) => option.flags),
    ),
  );
  const lines = [
    "# reddit-scrutinizer fish completions. Generated by `reddit-scrutinizer completions fish`.",
    "",
    "function __fish_reddit_scrutinizer_accepts_positional",
    "    set -l tokens (commandline -cx)",
    "    if test (count $tokens) -gt 0",
    "        switch $tokens[-1]",
    ...valueFlags.flatMap((flag) => [`            case '${flag}'`, "                return 1"]),
    "        end",
    "    end",
    "    return 0",
    "end",
    "",
    "complete -c reddit-scrutinizer -f",
  ];

  for (const option of model.options) lines.push(optionLine(option, rootCondition));
  for (const command of model.subcommands) {
    lines.push(
      `complete -c reddit-scrutinizer -n '__fish_use_subcommand' -a '${command.name}' -d '${escape(command.description)}'`,
    );
    const condition = `__fish_seen_subcommand_from ${command.name}`;
    for (const option of command.options) lines.push(optionLine(option, condition));
    const argument = command.arguments.at(0);
    if (argument?.kind === "choices") {
      lines.push(
        `complete -c reddit-scrutinizer -n '${condition}' -a '${argument.choices.join(" ")}' -d '${escape(argument.description)}'`,
      );
    }
    if (argument?.kind === "file") {
      lines.push(
        `complete -c reddit-scrutinizer -n '${condition}; and __fish_reddit_scrutinizer_accepts_positional' -F`,
      );
    }
    if (argument?.kind === "directory") {
      lines.push(
        `complete -c reddit-scrutinizer -n '${condition}; and __fish_reddit_scrutinizer_accepts_positional' -a '(__fish_complete_directories)'`,
      );
    }
  }

  lines.push(
    `complete -c reddit-scrutinizer -n '__fish_reddit_scrutinizer_accepts_positional; and not __fish_seen_subcommand_from ${commandNames}' -a '(__fish_complete_directories)' -d 'project directory'`,
    "",
  );
  return lines.join("\n");
}
