import type { CompletionModel, CompletionOption } from "./model";

function quote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function array(values: string[]): string {
  return `@(${values.map(quote).join(", ")})`;
}

function allOptions(model: CompletionModel): CompletionOption[] {
  return [model, ...model.subcommands].flatMap((command) => command.options);
}

export function render(model: CompletionModel): string {
  const commands = model.subcommands.map((command) => command.name);
  const optionSets = model.subcommands
    .map(
      (command) =>
        `  ${quote(command.name)} = ${array(command.options.flatMap((option) => option.flags))}`,
    )
    .join("\n");
  const choices = new Map<string, string[]>();
  const fileFlags = new Set<string>();
  const directoryFlags = new Set<string>();
  for (const option of allOptions(model)) {
    for (const flag of option.flags) {
      if (option.kind === "choices") choices.set(flag, option.choices);
      if (option.kind === "file") fileFlags.add(flag);
      if (option.kind === "directory") directoryFlags.add(flag);
    }
  }
  const choiceSets = Array.from(
    choices,
    ([flag, values]) => `  ${quote(flag)} = ${array(values)}`,
  ).join("\n");
  const shells =
    model.subcommands.find((command) => command.name === "completions")?.arguments.at(0)?.choices ??
    [];

  return `# reddit-scrutinizer PowerShell completions. Generated by \`reddit-scrutinizer completions powershell\`.
using namespace System.Management.Automation

Register-ArgumentCompleter -Native -CommandName 'reddit-scrutinizer' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)

  $commands = ${array(commands)}
  $rootOptions = ${array(model.options.flatMap((option) => option.flags))}
  $commandOptions = @{
${optionSets}
  }
  $choiceValues = @{
${choiceSets}
  }
  $fileFlags = ${array([...fileFlags])}
  $directoryFlags = ${array([...directoryFlags])}
  $elements = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
  $currentIsElement = $elements.Count -gt 0 -and $elements[-1] -eq $wordToComplete
  $previousIndex = if ($currentIsElement) { $elements.Count - 2 } else { $elements.Count - 1 }
  $previous = if ($previousIndex -ge 0) { $elements[$previousIndex] } else { '' }
  $subcommand = $commands | Where-Object { $elements -contains $_ } | Select-Object -First 1
  $candidates = @()

  if ($choiceValues.ContainsKey($previous)) {
    $candidates = $choiceValues[$previous]
  } elseif ($fileFlags -contains $previous) {
    $candidates = Get-ChildItem -Name -Path "$wordToComplete*" -File -ErrorAction SilentlyContinue
  } elseif ($directoryFlags -contains $previous) {
    $candidates = Get-ChildItem -Name -Path "$wordToComplete*" -Directory -ErrorAction SilentlyContinue
  } elseif ($wordToComplete.StartsWith('-')) {
    $candidates = if ($subcommand) { $commandOptions[$subcommand] } else { $rootOptions }
  } elseif ($subcommand -eq 'completions') {
    $candidates = ${array(shells)}
  } elseif ($subcommand -eq 'serve') {
    $candidates = Get-ChildItem -Name -Path "$wordToComplete*" -File -ErrorAction SilentlyContinue
  } else {
    $candidates = $commands + @(Get-ChildItem -Name -Path "$wordToComplete*" -Directory -ErrorAction SilentlyContinue)
  }

  $candidates |
    Where-Object { $_ -like "$wordToComplete*" } |
    Sort-Object -Unique |
    ForEach-Object { [CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
}
