import type { CompletionModel, CompletionOption } from "./model";

function escape(value: string): string {
  return value.replaceAll("'", "'\\''").replaceAll("[", "\\[").replaceAll("]", "\\]");
}

function escapeChoiceDescription(value: string): string {
  return escape(value).replaceAll(":", "\\:").replaceAll(" ", "\\ ");
}

function optionSpecs(option: CompletionOption): string[] {
  const description = escape(option.description);
  const valueName = option.valueName ?? "value";
  let value = "";
  if (option.kind === "choices") value = `:${valueName}:(${option.choices.join(" ")})`;
  if (option.kind === "file") value = `:${valueName}:_files`;
  if (option.kind === "directory") value = `:${valueName}:_directories`;
  if (option.kind === "value") value = `:${valueName}:`;
  return option.flags.map((flag) => `'${flag}[${description}]${value}'`);
}

function argumentSpec(command: CompletionModel, position: number): string | undefined {
  const argument = command.arguments.at(0);
  if (!argument) return undefined;
  if (argument.kind === "choices") {
    return `'${position}:${argument.name}:(${argument.choices.join(" ")})'`;
  }
  if (argument.kind === "file") return `'${position}:${argument.name}:_files'`;
  if (argument.kind === "directory") return `'${position}:${argument.name}:_directories'`;
  return `'${position}:${argument.name}:'`;
}

function lines(specs: string[]): string {
  return specs.map((spec) => `        ${spec} \\`).join("\n");
}

export function render(model: CompletionModel): string {
  const commandChoices = model.subcommands
    .map((command) => `${command.name}\\:${escapeChoiceDescription(command.description)}`)
    .join(" ");
  const branches = model.subcommands
    .map((command) => {
      const specs = command.options.flatMap(optionSpecs);
      const argument = argumentSpec(command, 1);
      if (argument) specs.push(argument);
      return `        ${command.name})
          _arguments \\
${lines(specs)}
          && return 0
          ;;`;
    })
    .join("\n");
  const rootSpecs = model.options.flatMap(optionSpecs);

  return `#compdef reddit-scrutinizer
# reddit-scrutinizer zsh completions. Generated by \`reddit-scrutinizer completions zsh\`.

_reddit_scrutinizer() {
  local context state line
  _arguments -C \\
${lines(rootSpecs)}
    '1:project directory or command:->target' \\
    '*::argument:->args' \\
    && return 0

  case "$state" in
    target)
      _alternative \\
        'commands:command:((${commandChoices}))' \\
        'directories:project directory:_directories'
      ;;
    args)
      case "$line[1]" in
${branches}
        *) _directories ;;
      esac
      ;;
  esac
}

compdef _reddit_scrutinizer reddit-scrutinizer
`;
}
